#!/bin/bash

log() {
  echo "$(date): $@"
}

wait_all_worker() {
  sleep 2
  while true;
  do
    rkt list --no-legend | grep running | grep worker &>/dev/null || break
    log "Services are still alive; keep waiting ..."
    sleep 5;
  done
  log "Done waiting!"
}

services=""

for job in $@;
do
  services="$services worker@$job.service"
done

log "Services: $services"

wait_all_worker
log "running rkt gc ..."
rkt gc --grace-period=0
log "Starting services: $services"
systemctl start $services
log "Sleeping for 32m before checking ..."
sleep 32m
log "Waiting for services to finish: $services"
wait_all_worker

